### ISSUE TITLE
Add support for 'batch' command

### ISSUE THREAD

**Issue by shpikat** [soywiz/typescript-node-definitions#55]
As per [documentation](https://github.com/NodeRedis/node_redis#clientbatchcommands):

> Identical to .multi without transactions. This is recommended if you want to execute many commands at once but don't have to rely on transactions

**Comment by soywiz** [comment]
Not maintaining this repo anymore. 
You should use: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by shpikat** [comment]
@soywiz got it, thanks!
